server:
  port: 8080
  servlet:
    context-path: /
spring:
  application.name: jetsons-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  pid.file: ${java.io.tmpdir}/jetsons-service-api.pid
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: jetsons-service-dbconnectionpool
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5401/jetsons
    username: postgres
    password: jetsons
server:
  port: 8018
springfox:
  documentation:
    swagger:
      v2:
        host: localhost:8018
---

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_db
  flyway:
    enabled: false
  jpa:
    show-sql: false
    database: h2
    hibernate:
      ddl-auto: create
logging:
  level:
    root: error
